// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWu-ctvUIehLBzNPGmpD9tOvvJ3rUT13I',
    appId: '1:564586279542:web:f90dc5ad3e1bd28fc1e557',
    messagingSenderId: '564586279542',
    projectId: 'class-activity-12',
    authDomain: 'class-activity-12.firebaseapp.com',
    storageBucket: 'class-activity-12.appspot.com',
    measurementId: 'G-DX1GSB8M5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRgWc2kzJBpOgi9PZPbiXxOFLr5bjJIzA',
    appId: '1:564586279542:android:79e426f7031a3268c1e557',
    messagingSenderId: '564586279542',
    projectId: 'class-activity-12',
    storageBucket: 'class-activity-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXGlrZIArGX0x6vgtjh1A6mkh0sACnbA',
    appId: '1:564586279542:ios:fd496aecd86670fac1e557',
    messagingSenderId: '564586279542',
    projectId: 'class-activity-12',
    storageBucket: 'class-activity-12.appspot.com',
    iosBundleId: 'com.example.activity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdXGlrZIArGX0x6vgtjh1A6mkh0sACnbA',
    appId: '1:564586279542:ios:175e09daa445dc40c1e557',
    messagingSenderId: '564586279542',
    projectId: 'class-activity-12',
    storageBucket: 'class-activity-12.appspot.com',
    iosBundleId: 'com.example.activity12.RunnerTests',
  );
}
